apiVersion: v1
kind: Secret
metadata:
  name: "loki"
  namespace: {{ .Release.Namespace }}
  labels:
    app: "loki"
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  loki.yaml: {{ tpl (toYaml .Values.lokiconfig) . | b64enc}}
