apiVersion: v1
kind: Service
metadata:
  labels:
    app: loki
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: Tiller
    io.cattle.field/appId: loki
    release: loki
  name: loki
  namespace: grafana
  resourceVersion: "2760571"
spec:
  clusterIP: ""
  ports:
  - name: http-metrics
    port: 3100
    protocol: TCP
    targetPort: http-metrics
  selector:
    app: loki
    release: loki
  sessionAffinity: None
  type: ClusterIP
