apiVersion: v1
kind: Service
metadata:
  labels:
    app: loki
    chart: loki-0.14.0
    heritage: Tiller
    io.cattle.field/appId: loki
    release: loki
  name: loki-headless
  namespace: grafana
  resourceVersion: "2760566"
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 3100
    protocol: TCP
    targetPort: http-metrics
  selector:
    app: loki
    release: loki
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}