apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: promtail
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: promtail
  namespace: {{ .Release.Namespace }}